### ISSUE TITLE
Module not shown as "Up to date" on available updates report

### ISSUE THREAD

**Issue by izmeez** [d6lts/update_advanced#1]
Thanks for incorporating changes to the update_advanced module to make it compatible with mydropwizard.

Unfortunately, the current version 1.2 does not show with
"drush --release-backend=mydropwizard rl update_advanced"

Also after manually download and install of version 1.2 the available updates report does not show the module as "Up to date" but as "Not supported".

It would be terrific if this can be fixed. Thanks.

**Comment by dsnopek** [comment]
Hm, the update status data didn't regenerate automatically for some reason. I've manually triggered the regeneration and version 1.2 should be recognized now:

https://updates.mydropwizard.com/files/update/v1/6.x/update_advanced.xml

Thanks for catching this!

**Comment by izmeez** [comment]
Comparing the current code with the patch in [module ready to apply to D6LTS](https://www.drupal.org/project/d6lts/issues/2711755) the following change in update_advanced.compare.inc removes the conditional:

```
-if ($mdw) {
-  // Make sure we always have /modules/mydropwizard/mydropwizard.compare.inc loaded.
-  module_load_include('inc', 'mydropwizard', 'mydropwizard.compare');
-}
-else {
-  // Make sure we always have /modules/update/update.compare.inc loaded.
-  module_load_include('inc', 'update', 'update.compare');
-}
+// Make sure we always have /modules/mydropwizard/mydropwizard.compare.inc loaded.
+module_load_include('inc', 'mydropwizard', 'mydropwizard.compare');
+// Make sure we always have /modules/update/update.compare.inc loaded.
+module_load_include('inc', 'update', 'update.compare');
```
Is this correct? Doesn't the core update module need to be disabled when using mydropwizard?

**Comment by dsnopek** [comment]
Hm. The current code isn't ideal. I changed it because I really didn't like the use of the `$mdw` global, but it probably should have an `if (module_exists('mydropwizard'))` and similar for 'update' in there. In any case, it should still work, it could just lead to accidentally loading a file at ./update.compare.inc or ./mydropwizard.compare.inc (depending on which one is disabled) if you happen to have such a file in your Drupal root.

I'd be happy to merge a PR that cleans this up! Otherwise, I'll get to eventually.

**Comment by izmeez** [comment]
Would this work?
```
if (module_exists('mydropwizard')) {
  // Make sure we always have /modules/mydropwizard/mydropwizard.compare.inc loaded.
  module_load_include('inc', 'mydropwizard', 'mydropwizard.compare');
}
else {
  // Make sure we always have /modules/update/update.compare.inc loaded.
  module_load_include('inc', 'update', 'update.compare');
}

```

**Comment by dsnopek** [comment]
Yeah, I think that'd be fine, it matches the other conditionals throughout the module.

**Comment by izmeez** [comment]
ok, I opened a PR with the addition of the conditional code.

Also, back on the first comment, the current version shows on the available updates page with correct links to the github.com/d6lts/update_advanced/ pages but still shows as "Not supported!" and still does not show with "drush --release-backend=mydropwizard rl update_advanced". Is it just a matter of being more patient or something else? Thanks.

**Comment by dsnopek** [comment]
Thanks!

I think I've got the "Not supported" thing fixed - can you give it a try again?

**Comment by izmeez** [comment]
Just checked and yes it is working now. Thanks for fixing it.

**Comment by dsnopek** [comment]
Great, thanks!
